version: '2'
services:
    web:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/vikings
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - "6379"